version: '2'

services:

  web:
    build:
      context: .
    ports:
      - 5000:5000

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    links:
      - web
